return {
  { "dasupradyumna/midnight.nvim", lazy = false },
  { "ellisonleao/gruvbox.nvim", config = true, contrast = "hard" },
  { "catppuccin/nvim", name = "catppuccin" },
  { "sainnhe/everforest" },
  { "LazyVim/LazyVim", opts = { colorscheme = "vim" } },
  { "rebelot/kanagawa.nvim" },
  { "kepano/flexoki-neovim" },
  { "everviolet/nvim" },
  { "nyoom-engineering/nyoom.nvim" },
  { "metalelf0/black-metal-theme-neovim" },
  { "zenbones-theme/zenbones.nvim", dependencies = "rktjmp/lush.nvim" },
  { "savq/melange-nvim" },
  { "maxmx03/solarized.nvim" },
  { "dasupradyumna/midnight.nvim", lazy = false, priority = 1000 },
  { "ellisonleao/gruvbox.nvim", config = true },
  { "catppuccin/nvim", name = "catppuccin" },
  { "sainnhe/everforest" },
  { "rebelot/kanagawa.nvim" },
  { "kepano/flexoki-neovim" },
  { "everviolet/nvim" },
  { "nyoom-engineering/nyoom.nvim" },
  { "mrtazz/molokai.vim" },
  { "petrblaho/herald.vim" },
}
